# Generated by Django 4.2.5 on 2023-10-02 20:18

from django.db import migrations
import djangocms_frontend.contrib.image.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("djangocms_frontend", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[],
            options={
                "verbose_name": "Person",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=(
                djangocms_frontend.contrib.image.models.ImageMixin,
                "djangocms_frontend.frontenduiitem",
            ),
        ),
    ]
