# Generated by Django 5.2.4 on 2025-07-23 08:14

import cms_theme.models
import djangocms_frontend.contrib.image.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_theme', '0001_initial'),
        ('djangocms_frontend', '0002_migrate_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudyProfile',
            fields=[
            ],
            options={
                'verbose_name': 'Case study profile',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('djangocms_frontend.frontenduiitem',),
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
            ],
            options={
                'verbose_name': 'Feature',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('djangocms_frontend.frontenduiitem',),
        ),
        migrations.CreateModel(
            name='PromoCard',
            fields=[
            ],
            options={
                'verbose_name': 'Promo card',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(djangocms_frontend.contrib.image.models.ImageMixin, cms_theme.models.SquareThumbnailMixin, 'djangocms_frontend.frontenduiitem'),
        ),
    ]
