# Generated by Django 5.2.6 on 2026-01-15 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_theme', '0003_delete_casestudyprofile_delete_feature_and_more'),
        ('djangocms_frontend', '0002_migrate_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureHanging',
            fields=[
            ],
            options={
                'verbose_name': 'Feature hanging',
                'managed': False,
                'proxy': True,
            },
            bases=('djangocms_frontend.frontenduiitem',),
        ),
        migrations.CreateModel(
            name='HeroPlugin',
            fields=[
            ],
            options={
                'verbose_name': 'Hero',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('djangocms_frontend.frontenduiitem',),
        ),
    ]
