# Generated by Django 5.2.6 on 2026-01-15 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_theme', '0004_featurehanging_heroplugin'),
        ('djangocms_frontend', '0002_migrate_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
            ],
            options={
                'verbose_name': 'Counter',
                'managed': False,
                'proxy': True,
            },
            bases=('djangocms_frontend.frontenduiitem',),
        ),
    ]
